
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/red_green_blue?useUnicode=true&characterEncoding=utf-8&useSSL=true&verifyServerCertificate=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 980720
