spring:
  profiles:
    active: dev

mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  type-aliases-package: com.bst.red_green_blue.pojo
#  配置日志打印的等级
logging:
    level:
      com.bst.red_green_blue: DEBUG