spring:
  datasource:
    url: jdbc:mysql://45.63.59.19:3306/red_green_blue?useUnicode=true&characterEncoding=utf-8&useSSL=true&verifyServerCertificate=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: Bst12345687


mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  type-aliases-package: com.bst.red_green_blue.pojo
